blinklabs-io/adder

README.md
configs/snek.yaml.example
go.mod
go.sum
input/chainsync/chainsync.go
input/chainsync/options.go
input/chainsync/plugin.go

feat: easier config for chainsync input

---

Makefile
cmd/snek/main.go
internal/config/config.go
internal/version/version.go

feat: track and display version

---

cmd/snek/main.go
input/chainsync/plugin.go
output/log/plugin.go
plugin/register.go

feat: show description for plugins when listing

---

input/chainsync/block.go
input/chainsync/chainsync.go
input/chainsync/options.go
input/chainsync/plugin.go
input/chainsync/tx.go

feat: make block/tx event CBOR optional

---

cmd/snek/main.go
filter/event/event.go
filter/event/option.go
filter/event/plugin.go
filter/filter.go
input/chainsync/chainsync.go
pipeline/pipeline.go
plugin/option.go
plugin/register.go

feat: basic filter support

---

README.md
filter/chainsync/chainsync.go
filter/chainsync/option.go
filter/chainsync/plugin.go
filter/filter.go
go.mod
go.sum
input/chainsync/tx.go

feat: chainsync filter support

---

README.md
filter/chainsync/chainsync.go
go.mod
go.sum

feat: filtering on stake address

---

input/input.go
output/embedded/embedded.go
output/embedded/options.go
output/output.go

This output plugin is useful when using Snek as a library and you want to perform custom processing for events

feat: embedded output plugin

---

README.md
filter/chainsync/chainsync.go
filter/chainsync/option.go
filter/chainsync/plugin.go
filter/event/event.go
filter/event/option.go
filter/event/plugin.go

feat: support for multiple filter values

---

input/chainsync/chainsync.go
input/chainsync/options.go
input/chainsync/plugin.go

feat: chainsync bulk mode

---

output/notify/notify.go
output/notify/options.go
output/notify/plugin.go

Support setting the title of OS notifications.
Fixes #73

feat: notify title option

---

Makefile

fix(ci): static compile by disabling cgo

---

output/webhook/webhook.go

feat: improved discord output

---

api/api.go
output/push/push.go
output/push/qr_generator.go

- small push enhancment on block
- fix qrCode endpoint after page refresh string was concatenating

fix: api listen to all interfaces

---

cmd/snek/main.go
go.mod
go.sum
input/chainsync/chainsync.go
input/chainsync/options.go
input/chainsync/plugin.go

feat: auto-reconnect on connection failure in chainsync input

---

output/push/push.go

Send message example
```
Transaction Title: SnekTransaction Body: New Transaction!
BlockNumber: 9686131, SlotNumber: 111270607
Inputs: 1, Outputs: 2
Fee: 184685
Hash: 1ff9c21c5d01982e2563414adbe38252e11a3434e243d71b67a38ae5b3d50256
Metadata: {"674":{"msg":["Minswap: Swap Exact Out Order"]}}
```

feat: add cip20 message as metadata to push event notification

---

filter/chainsync/chainsync.go
input/chainsync/tx.go

feat: filtering tx by pool

---

input/chainsync/tx.go

feat: reference inputs in transaction events

---

output/webhook/options.go
output/webhook/plugin.go
output/webhook/webhook.go

fix: perform tls verification by default

---

api/api.go
output/push/qr_generator.go

fix: potentially unsafe quoting

---

filter/chainsync/chainsync.go

fix(filter): chainsync: use resolved inputs in matching

---

api/api.go

fix: default gin to release node

---

input/chainsync/chainsync.go
input/chainsync/chainsync_test.go

1. Added changes to update status while handling rollbackward
2. Added unit tests to test the changes to update the status

feat: status update on rollbackward

---

input/chainsync/tx.go

Feat: Transaction Witnesses

---

api/api_test.go
cmd/adder/main.go
event/event.go
filter/chainsync/chainsync_test.go
filter/event/event.go
input/chainsync/chainsync.go
internal/config/config.go
output/push/fcm/message.go
plugin/option.go
plugin/register.go

Also, simplify event loop with `slices.Contains`

fix: use any instead of interface{}

---

input/chainsync/chainsync.go
input/chainsync/chainsync_test.go

1. Added timeout for kupo client
2. Added unit test for the method
Closes #399

Added timeout for kupo client

---

filter/chainsync/chainsync_test.go
go.mod
go.sum
input/chainsync/transaction_output.go

chore(deps): update blinklabs-io/gouroboros to v0.130.1

---

input/chainsync/chainsync.go

fix: change log level to Warn
