blinklabs-io/adder

- input/chainsync/chainsync.go
- input/chainsync/options.go
> feat: chainsync input plugin status update callback

- api/api.go
- api/api_test.go
- cmd/snek/main.go
- output/push/api_routes.go
- output/push/qr_generator.go
> feat: add QRcode generate to scan it with snek mobile

- input/chainsync/block.go
- input/chainsync/chainsync.go
- input/chainsync/tx.go
- output/webhook/webhook.go
> feat: update discord links for known Cardano networks

- cmd/snek/main.go
- event/event.go
- fcm/message.go
- input/chainsync/chainsync.go
- input/chainsync/options.go
- input/chainsync/plugin.go
- input/chainsync/tx.go
- internal/config/config.go
- internal/logging/logging.go
- output/notify/notify.go
- output/push/push.go
- output/webhook/webhook.go
- pipeline/pipeline.go
- plugin/option.go
- plugin/register.go
Use
```
golines -w --ignore-generated --chain-split-dots --max-len=80 --reformat-tags .
```
> chore: run golines

- input/chainsync/block.go
- output/notify/notify.go
> feat: add transaction count to chainsync Block event

- filter/chainsync/chainsync.go
- filter/chainsync/option.go
- filter/chainsync/plugin.go
- filter/event/event.go
- filter/event/option.go
- filter/event/plugin.go
- input/chainsync/chainsync.go
- input/chainsync/options.go
- input/chainsync/plugin.go
- output/log/log.go
- output/log/options.go
- output/log/plugin.go
- output/notify/notify.go
- output/notify/options.go
- output/notify/plugin.go
- output/push/options.go
- output/push/plugin.go
- output/push/push.go
- output/webhook/options.go
- output/webhook/plugin.go
- output/webhook/webhook.go
- plugin/log.go
> feat: plugin logging framework

- api/api.go
- cmd/snek/main.go
- configs/snek.yaml.example
- internal/config/config.go
> feat: add API global config for host,port

- input/chainsync/chainsync.go
> fix: auto-reconnect on handshake failure

- input/chainsync/chainsync.go
> fix: don't overwrite intersect with empty cursor cache

- input/chainsync/block.go
- input/chainsync/tx.go
This allows access to all underlying block/TX attributes when embedding snek as a library
> feat: include original block/TX object in chainsync events

- input/chainsync/chainsync.go
> feat: auto-reconnect backoff for chainsync input

- go.mod
- go.sum
- input/chainsync/chainsync.go
- input/chainsync/transactionOutput.go
- input/chainsync/transactionOutput_test.go
- internal/logging/kugoCustomLogger.go
add custom KugoLogger to suppress debug logs
fixes #259
> fix: update address conversion with updated NewAddress

- input/chainsync/tx.go
As title says, adds staking withdrawals information to tx events. Closes #241
Tested manually on tx hash `3cd223934d556c4f599055cad6257992d20a7b37418c7d864a987fc91109be48` and 
```yaml
intersect-point: 140137291.eef70ed5877425b4059f5c139e8ebaef4f01c3ae33aa9a788a670913daf2ce14
```
logs out:
```bash
...
"withdrawals":{"stake1u9gumv8sjecsga0frqg40l66y3arl7xnu8cj237z93csxyscsg85a":68737598}
...
```
as expected :relieved:
> feat: add withdrawals field to transaction events

- output/notify/notify.go
Sure, it's an icon, but it's also in the user's cache directory and nobody should be poking around in there anyway.
> fix(notify): tighten permissions to only user on icon file

- filter/chainsync/chainsync_test.go
- filter/chainsync/plugin_test.go
1. Added unit test for chainsync fliter plugin framework.
2. Added additional unit tests to test filtering events by address, policy/asset, pool ID
> test: added unit tests for chainsync filter plugin

- filter/chainsync/chainsync.go
- filter/chainsync/chainsync_test.go
1. Added changes to check StakeDeregistrationCertificate and StakeDelegationCertificate StakeCredential against given address
2. Updated existing unit test to add testcases for above scenarios
Closes #313
> feat(filter): check StakeDeregistrationCertificate and StakeDelegationCertificate StakeCredential 

- filter/chainsync/chainsync_test.go
1. Updated test cases to use the renamed and fixed-size common.Credential struct instead of the old common.StakeCredential struct.
2. Aligned stake address generation in tests with production logic by using Credential.Hash() and bech32 encoding to ensure accurate filter matching.
3. Tested the changes and now all the test cases are working.
Closes #393
> fix(chainsync): Updated tests to use renamed and fixed-size Credentia Struct

- go.mod
- go.sum
- input/chainsync/block.go
- input/chainsync/block_test.go
- input/chainsync/chainsync.go
- input/chainsync/tx.go
> chore(deps): gouroboros 0.116.0

- input/chainsync/chainsync.go
- input/chainsync/options.go
- input/chainsync/plugin.go
> feat: configurable delay confirmations for chainsync events

- filter/chainsync/chainsync_test.go
- go.mod
- go.sum
- input/chainsync/block_test.go
- input/chainsync/transaction_output.go
> chore(deps): update blinklabs-io/gouroboros to v0.127.0

- .github/workflows/ci-docker.yml
- .github/workflows/publish.yml
> ci: use split native builds for images

- input/chainsync/chainsync.go
- input/chainsync/options.go
- input/chainsync/plugin.go
- internal/config/config.go
closes #349
BREAKING CHANGE when starting Adder with Kupo
- set KUPO_URL or kupo_url in yaml config
> refactor(chainsync): always initialize kupoUrl from global config
